stages:
  - dependencies:
    - init
    name: madgraph
    scheduler:
      parameters:
         proc_card: {output: proc_card, step: init}
         param_card: {output: param_card, step: init}
         run_card: {output: run_card, step: init}
         ufotar: {output: ufotar, step: init}
         n_events: {output: n_events, step: init}
         outputlhe: "{workdir}/events.lhe"
      scheduler_type: singlestep-stage
      step:
        environment:
          environment_type: docker-encapsulated
          image: recast/madgraph
          imagetag: '2.6.7_v2'
        process:
          process_type: string-interpolated-cmd
          cmd: python steer_madgraph.py {proc_card} {outputlhe} --ufotar {ufotar} -n {n_events} --param_card {param_card} --run_card {run_card}
        publisher:
          outputmap:
            lhefile: outputlhe
          publisher_type: frompar-pub
